<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="CP-156-CS-55" failures="2" tests="19" name="ibportal.useAccount" time="88.836" errors="0" timestamp="2025-09-26T14:41:02 IST" skipped="0">
  <testcase classname="ibportal.useAccount" name="createOrUpdateAccount" time="1.808"/>
  <testcase classname="ibportal.useAccount" name="createOrUpdateAccount" time="6.137"/>
  <testcase classname="ibportal.useAccount" name="crossCase_getMerchantWithoutKyc" time="3.972"/>
  <testcase classname="ibportal.useAccount" name="crossCase_getComfirmationSubmissionWithoutKyc" time="1.979"/>
  <testcase classname="ibportal.useAccount" name="crossCase_KycThenShopWithoutChannel" time="37.574"/>
  <testcase classname="ibportal.useAccount" name="updateChannels" time="2.102"/>
  <testcase classname="ibportal.useAccount" name="updateKyc" time="2.925"/>
  <testcase classname="ibportal.useAccount" name="updateKyc" time="3.679"/>
  <testcase classname="ibportal.useAccount" name="fetchDetails" time="3.305"/>
  <testcase classname="ibportal.useAccount" name="deleteMerchants" time="2.456"/>
  <testcase classname="ibportal.useAccount" name="deleteMerchants" time="3.383"/>
  <testcase classname="ibportal.useAccount" name="validateDeletedMerchants" time="1.670">
    <failure message="❌ No nested Merchants found for MID: 68d6584c8200d99ebea8cb3d" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: ❌ No nested Merchants found for MID: 68d6584c8200d99ebea8cb3d
at ibportal.useAccount.validateDeletedMerchants(useAccount.java:443)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- validateDeletedMerchants -->
  <testcase classname="ibportal.useAccount" name="createOrUpdateShopDetails" time="5.916"/>
  <testcase classname="ibportal.useAccount" name="updateConfirmPage" time="2.585"/>
  <testcase classname="ibportal.useAccount" name="updateConfirmPage" time="1.704"/>
  <testcase classname="ibportal.useAccount" name="verifyOtpPage" time="2.867"/>
  <testcase classname="ibportal.useAccount" name="verifyOtpPage" time="1.720">
    <failure message="Status mismatch for test case: Invalid OTP Test expected [failed] but found [success]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Status mismatch for test case: Invalid OTP Test expected [failed] but found [success]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at ibportal.useAccount.verifyOtpPage(useAccount.java:565)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyOtpPage -->
  <testcase classname="ibportal.useAccount" name="verifySubmitPage" time="2.145"/>
  <testcase classname="ibportal.useAccount" name="verifySubmitPage" time="0.909"/>
</testsuite> <!-- ibportal.useAccount -->
